spring:
  #redis配置信息
  redis:
    host: 127.0.0.1
    port: 6379
    database: 10
  #数据库连接配置信息
  datasource:
    url: jdbc:mysql://119.23.242.234:9306/wxdc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://47.98.39.45:9097/wxdc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
#    url: jdbc:mysql://127.0.0.1:3306/wxdc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
#  boot:
#    admin:
#      url: http://127.0.0.1:9078
#      client:
#         name: WD-BIZ
#management.security.enabled: false

server:
  port: 8081

#ticserver:
#  url: http://127.0.0.1:9095/api/push/carcmd
biz:
  scTime: 30000

staticPath:  D:\static\common\
znzpurl: http://127.0.0.1:9888/api
obdCheckUrl: http://119.23.242.234:9082/api/3007
videoPath: http://www.168car.net:9091/test/
#updateMediaUrl:
#deleteZnzpRedisKeyUrl:
